### ISSUE TITLE
Camera effect bugs

### ISSUE THREAD

**Issue by LucasGundehug** [KrewsOrg/Arcturus-Community#13]
Effect procents
Effects (If they exist) gets automatically turned into 100%, even IF you make the effect amount 10%.
2+ effects = broken image
Example 1: http://arcturus.pw/camera/SpeedHotelli/7_1541009829.png
Example 2 You get the point: http://arcturus.pw/camera/SpeedHotelli/7_1541010083.png
+ idea
Extra plus would be generating figuredatas through your own gamedata. This could be configured through config.ini or emulator_settings.
Example: http://arcturus.pw/camera/SpeedHotelli/88_1541345041.png
Thank you for your time.

**Comment by benycodes** [comment]
Problem not related to Arcturus Morningstar.
Related to TheGeneral's camera server.

Alternative plugin can be used:
http://forum.ragezone.com/f353/arcturus-png-camera-1160123/
